_extends: .github

repository:
  name: NucleosSeoBundle
  description: 🔌 Seo components.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, seo, breadcrumb
